package co.pablob.mongo.control;

public interface Constants {

    String ENV_MONGO_USERNAME = "MONGO_USERNAME";
    String ENV_MONGO_PASSWORD = "MONGO_PASSWORD";
    String ENV_MONGO_SERVER = "MONGO_SERVER";
    String ENV_MONGO_PORT = "MONGO_PORT";
    String ENV_MONGO_CONNECTION_STRING = "MONGO_CONNECTION_STRING";
    String ENV_DATABASE_NAME = "DATABASE_NAME";
    String ENV_BUILD_CONNECTION_STRING = "BUILD_CONNECTION_STRING";
    String ENV_MONGO_OPTIONS = "MONGO_OPTIONS";
    String ENV_MONGO_PROCESS_CUSTOMIZER_ALL_DATABASES = "MONGO_PROCESS_CUSTOMIZER_ALL_DATABASES";

    String DEFAULT_DATABASE_NAME = "test";
    String DEFAULT_MONGO_SERVER = "localhost";
}
