== Default behaviour

By default the `{library_name}` library will run connecting to `localhost`
though `27017` port without certificate and creating a database called
`avalane`.

This behaviour can be changed setting some environment variables in the host
overriding the default values.

=== Available environment variables

[%header,cols=3*]
|====
| Environment variable Name
| Description
| Default value

| MONGO_USERNAME
| User name to connect to MongoDB server
| `<Empty>`

| MONGO_PASSWORD
| Password of the defined username
| `<Empty>`

| MONGO_SERVER
| Hostname of the MongoDB server
| localhost

| MONGO_PORT
| Port of the MongoDB server
| 27017

| DATABASE_NAME
| Database name
| avalane

| MONGO_OPTIONS
| Mongo options that will be attached in string built if
`BUILD_CONNECTION_STRING` is set to `true`
| `<Empty>`

| BUILD_CONNECTION_STRING
| If `true` a connection string will be build with values
in `MONGO_USERNAME`, `MONGO_PASSWORD`, `MONGO_SERVER`, `MONGO_PORT`,
 `DATABASE_NAME` and `MONGO_OPTIONS`
| `false`

| MONGO_CONNECTION_STRING
| Connection string
| `<Empty>`
|====

=== Mongo JDBC

{library_name} uses Mongo JDBC driver version {mongojdbc-version}.

This library is a transitive dependency what means it is not needed to
add the JDBC mongo driver when this library is used, only adding
the {library_name} as dependency it's enough to start to work with mongo
in the application.


